from image.report_generator.utils.generic import ElementStyling, Position


styling_dict = {
    "binance_1": {
        "vertical_line_1": ElementStyling(position=Position(0.24, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.38, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.41, 0.285),
            font="BinancePlex.otf",
            font_size=22,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.285),
            font="BinancePlex.otf",
            font_size=22,
            short_color="#b6536c",
            long_color="#438A70",
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.285),
            font="BinancePlex.otf",
            font_size=22,
            color=(255, 255, 255),
        ),
        "roi": ElementStyling(
            position=Position(0.11, 0.35),
            font="BinancePlex.otf",
            font_size=65,
            color=(52, 183, 133),
        ),
        "entry": ElementStyling(
            position=Position(0.4792, 0.548),
            font="BinancePlex.otf",
            font_size=20,
            color=(237, 187, 54),
        ),
        "target": ElementStyling(
            position=Position(0.4792, 0.6),
            font="BinancePlex.otf",
            font_size=20,
            color=(237, 187, 54),
        ),
        "referral": ElementStyling(
            position=Position(0.23, 0.766),
            font="BinancePlex.otf",
            font_size=28,
            color=(255, 255, 255),
        ),
        "qr_code": ElementStyling(position=Position(117 / 1035, 460 / 624), size=64),
    },
    "binance_2": {
        "vertical_line_1": ElementStyling(position=Position(0.2328, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.34, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.372, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            short_color="#b6536c",
            long_color="#438A70",
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            color=(255, 255, 255),
        ),
        "roi": ElementStyling(
            position=Position(0.11, 0.35),
            font="BinancePlex.otf",
            font_size=90,
            color=(52, 183, 133),
        ),
        "entry": ElementStyling(
            position=Position(0.4792, 0.548),
            font="DIN 2014 Demi.ttf",
            font_size=30,
            color=(237, 187, 54),
        ),
        "target": ElementStyling(
            position=Position(0.4792, 0.6),
            font="DIN 2014 Demi.ttf",
            font_size=30,
            color=(237, 187, 54),
        ),
        "referral": ElementStyling(
            position=Position(0.23, 0.7836),
            font="BAHNSCHRIFT 1.TTF",
            font_size=40,
            color=(255, 255, 255),
        ),
        "qr_code": ElementStyling(position=Position(112 / 980, 457 / 619), size=94),
    },
    "binance_3": {
        "vertical_line_1": ElementStyling(position=Position(0.2328, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.34, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.372, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            short_color="#b6536c",
            long_color="#438A70",
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            color=(255, 255, 255),
        ),
        "roi": ElementStyling(
            position=Position(0.11, 0.35),
            font="BinancePlex.otf",
            font_size=90,
            color=(52, 183, 133),
        ),
        "entry": ElementStyling(
            position=Position(0.4792, 0.548),
            font="DIN 2014 Demi.ttf",
            font_size=30,
            color=(237, 187, 54),
        ),
        "target": ElementStyling(
            position=Position(0.4792, 0.6),
            font="DIN 2014 Demi.ttf",
            font_size=30,
            color=(237, 187, 54),
        ),
        "referral": ElementStyling(
            position=Position(0.243, 0.79),
            font="BAHNSCHRIFT 1.TTF",
            font_size=40,
            color=(255, 255, 255),
        ),
        "qr_code": ElementStyling(position=Position(118 / 980, 460 / 619), size=94),
    },
    "binance_4": {
        "vertical_line_1": ElementStyling(position=Position(0.2328, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.34, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.5, 0.4085),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=43,
            color="black",
        ),
        "signal_type": ElementStyling(
            position=Position(0.5, 0.456),
            font="IBMPlexSans-Regular.ttf",
            font_size=34,
            short_color=(217, 83, 116),
            long_color=(52, 183, 133),
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            color=(255, 255, 255),
        ),
        "roi": ElementStyling(
            position=Position(0.5, 0.512),
            font="BinancePlex.otf",
            font_size=110,
            color=(46, 189, 136),
        ),
        "entry": ElementStyling(
            position=Position(0.29, 0.684),
            font="DIN 2014 Demi.ttf",
            font_size=36,
            color="black",
        ),
        "target": ElementStyling(
            position=Position(0.7, 0.684),
            font="DIN 2014 Demi.ttf",
            font_size=36,
            color="black",
        ),
        "referral": ElementStyling(
            position=Position(0.33, 0.946),
            font="DIN Next CYR Medium.ttf",
            font_size=30,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(0.76, 0.85), size=153),
        "gen_date": ElementStyling(
            position=Position(0.5, 0.768),
            font="DINNextCYR-Regular.ttf",
            font_size=30,
            color="#999999",
        ),
        "draw_datetime": True,
    },
    "binance_5": {
        "vertical_line_1": ElementStyling(position=Position(0.2328, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.34, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.5, 0.4085),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=43,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.5, 0.456),
            font="IBMPlexSans-Regular.ttf",
            font_size=34,
            short_color=(217, 83, 116),
            long_color=(52, 183, 133),
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.287),
            font="BAHNSCHRIFT 1.TTF",
            font_size=30,
            color=(255, 255, 255),
        ),
        "roi": ElementStyling(
            position=Position(0.5, 0.512),
            font="BinancePlex.otf",
            font_size=110,
            color=(46, 189, 136),
        ),
        "entry": ElementStyling(
            position=Position(0.29, 0.684),
            font="DIN 2014 Demi.ttf",
            font_size=36,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.7, 0.684),
            font="DIN 2014 Demi.ttf",
            font_size=36,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.33, 0.946),
            font="DIN Next CYR Medium.ttf",
            font_size=30,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.764, 0.854), size=143),
        "gen_date": ElementStyling(
            position=Position(0.5, 0.768),
            font="DINNextCYR-Regular.ttf",
            font_size=30,
            color="#999999",
        ),
        "draw_datetime": True,
    },
    "binance_6": {
        "vertical_line_1": ElementStyling(position=Position(0.2328, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.34, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.062, 0.308),
            font="Metropolis-Bold.otf",
            font_size=47,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.062, 0.36),
            font="Metropolis-Medium.otf",
            font_size=34,
            short_color=(217, 83, 116),
            long_color=(52, 183, 133),
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.287),
            font="Metropolis-Medium.otf",
            font_size=35,
            color=(140, 140, 140),
        ),
        "roi": ElementStyling(
            position=Position(0.055, 0.437),
            font="Metropolis-Bold.otf",
            font_size=110,
            color=(46, 189, 136),
        ),
        "entry": ElementStyling(
            position=Position(0.062, 0.619),
            font="Metropolis-Medium.otf",
            font_size=38,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.513, 0.619),
            font="Metropolis-Medium.otf",
            font_size=38,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.33, 0.926),
            font="Metropolis-Medium.otf",
            font_size=34,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.782, 0.854), size=132),
        "gen_date": ElementStyling(
            position=Position(0.184, 0.112),
            font="Metropolis-Regular.otf",
            font_size=34,
            color="#999999",
        ),
        "username": ElementStyling(
            position=Position(0.182, 0.064),
            font="Metropolis-Bold.otf",
            font_size=44,
            color="white",
        ),
        "draw_datetime": True,
        "draw_username": True,
    },
    "binance_7": {
        "vertical_line_1": ElementStyling(position=Position(0.2328, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.34, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.062, 0.308),
            font="Metropolis-Bold.otf",
            font_size=47,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.062, 0.36),
            font="Metropolis-Medium.otf",
            font_size=34,
            short_color=(217, 83, 116),
            long_color=(52, 183, 133),
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.287),
            font="Metropolis-Medium.otf",
            font_size=35,
            color=(140, 140, 140),
        ),
        "roi": ElementStyling(
            position=Position(0.055, 0.437),
            font="Metropolis-Bold.otf",
            font_size=110,
            color=(46, 189, 136),
        ),
        "entry": ElementStyling(
            position=Position(0.062, 0.619),
            font="Metropolis-Medium.otf",
            font_size=38,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.513, 0.619),
            font="Metropolis-Medium.otf",
            font_size=38,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.33, 0.926),
            font="Metropolis-Medium.otf",
            font_size=34,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.782, 0.854), size=132),
        "gen_date": ElementStyling(
            position=Position(0.184, 0.112),
            font="Metropolis-Regular.otf",
            font_size=34,
            color="#999999",
        ),
        "username": ElementStyling(
            position=Position(0.182, 0.064),
            font="Metropolis-Bold.otf",
            font_size=44,
            color="white",
        ),
        "draw_datetime": True,
        "draw_username": True,
    },
    "binance_8": {
        "vertical_line_1": ElementStyling(position=Position(0.2328, 0.2885)),
        "vertical_line_2": ElementStyling(position=Position(0.34, 0.2885)),
        "symbol": ElementStyling(
            position=Position(0.062, 0.308),
            font="Metropolis-Bold.otf",
            font_size=47,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.062, 0.36),
            font="Metropolis-Medium.otf",
            font_size=34,
            short_color=(217, 83, 116),
            long_color=(52, 183, 133),
        ),
        "leverage": ElementStyling(
            position=Position(0.2734, 0.287),
            font="Metropolis-Medium.otf",
            font_size=35,
            color=(140, 140, 140),
        ),
        "roi": ElementStyling(
            position=Position(0.055, 0.437),
            font="Metropolis-Bold.otf",
            font_size=110,
            color=(46, 189, 136),
        ),
        "entry": ElementStyling(
            position=Position(0.062, 0.619),
            font="Metropolis-Medium.otf",
            font_size=38,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.513, 0.619),
            font="Metropolis-Medium.otf",
            font_size=38,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.33, 0.926),
            font="Metropolis-Medium.otf",
            font_size=34,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.782, 0.854), size=132),
        "gen_date": ElementStyling(
            position=Position(0.184, 0.112),
            font="Metropolis-Regular.otf",
            font_size=34,
            color="#999999",
        ),
        "username": ElementStyling(
            position=Position(0.182, 0.064),
            font="Metropolis-Bold.otf",
            font_size=44,
            color="white",
        ),
        "draw_datetime": True,
        "draw_username": True,
    },
    "bybit_1": {
        "symbol": ElementStyling(
            position=Position(0.045, 0.2),
            font="IBMPlexSans-Bold.ttf",
            font_size=60,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.21),
            font="IBMPlexSans-Medium.ttf",
            font_size=30,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.6,
            spacing=25,
            rect_radius=5,
            short_color=(220, 66, 90),
            long_color=(33, 182, 114),
            short_box_color=(64, 38, 39),
            long_box_color=(34, 51, 45),
        ),
        "roi": ElementStyling(
            position=Position(0.045, 0.35),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=100,
            color=(33, 182, 114),
        ),
        "entry": ElementStyling(
            position=Position(0.045, 0.57),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.222, 0.57),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.29, 0.88),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=50,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(0.842, 0.793), size=150),
    },
    "bybit_2": {
        "symbol": ElementStyling(
            position=Position(0.062, 0.175),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=55,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.187),
            font="IBMPlexSans-Regular.ttf",
            font_size=27,
            margin_x=8,
            margin_y=6,
            margin_y_mult=0.5,
            spacing=25,
            rect_radius=5,
            short_color=(220, 66, 90),
            long_color=(33, 182, 114),
            short_box_color=(64, 38, 39),
            long_box_color=(34, 51, 45),
        ),
        "roi": ElementStyling(
            position=Position(0.065, 0.3),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=95,
            color=(33, 182, 114),
        ),
        "entry": ElementStyling(
            position=Position(0.063, 0.468),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.063, 0.57),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.425, 0.919),
            font="IBMPlexSans-Medium.ttf",
            font_size=50,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(722 / 930, 1084 / 1280), size=161),
    },
    "bybit_3": {
        "symbol": ElementStyling(
            position=Position(0.045, 0.2),
            font="IBMPlexSans-Bold.ttf",
            font_size=60,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.21),
            font="IBMPlexSans-Medium.ttf",
            font_size=30,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            spacing=25,
            rect_radius=5,
            short_color=(220, 66, 90),
            long_color=(33, 182, 114),
            short_box_color=(64, 38, 39),
            long_box_color=(34, 51, 45),
        ),
        "roi": ElementStyling(
            position=Position(0.045, 0.35),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=100,
            color=(33, 182, 114),
        ),
        "entry": ElementStyling(
            position=Position(0.045, 0.57),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.235, 0.57),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.29, 0.88),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=50,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(0.842, 0.793), size=150),
    },
    "bybit_4": {
        "symbol": ElementStyling(
            position=Position(0.062, 0.17),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=60,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.18),
            font="IBMPlexSans-Regular.ttf",
            font_size=30,
            margin_x=8,
            margin_y=6,
            margin_y_mult=0.5,
            spacing=25,
            rect_radius=5,
            short_color=(220, 66, 90),
            long_color=(33, 182, 114),
            short_box_color=(64, 38, 39),
            # long_box_color=(34, 51, 45)),
            long_box_color=(47, 72, 51),
        ),
        "roi": ElementStyling(
            position=Position(0.065, 0.3),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=95,
            color=(33, 182, 114),
        ),
        "entry": ElementStyling(
            position=Position(0.063, 0.468),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.063, 0.57),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.425, 0.919),
            font="IBMPlexSans-Medium.ttf",
            font_size=50,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(722 / 930, 1084 / 1280), size=161),
    },
    "bybit_5": {
        "symbol": ElementStyling(
            position=Position(0.062, 0.17),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=60,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.116, 0.18),
            font="IBMPlexSans-Regular.ttf",
            font_size=30,
            margin_x=8,
            margin_y=6,
            margin_y_mult=0.5,
            spacing=25,
            rect_radius=5,
            short_color=(220, 66, 90),
            long_color=(33, 182, 114),
            short_box_color=(64, 38, 39),
            # long_box_color=(34, 51, 45)),
            long_box_color=(47, 72, 51),
        ),
        "roi": ElementStyling(
            position=Position(0.065, 0.3),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=95,
            color=(33, 182, 114),
        ),
        "entry": ElementStyling(
            position=Position(0.063, 0.468),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.063, 0.57),
            font="IBMPlexSans-SemiBold.ttf",
            font_size=45,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.425, 0.919),
            font="IBMPlexSans-Medium.ttf",
            font_size=50,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(722 / 930, 1084 / 1280), size=161),
    },
    "bitget_1": {
        "symbol": ElementStyling(
            position=Position(0.059, 0.348),
            font="Switzer-Semibold.otf",
            font_size=50.5,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.059, 0.419),
            font="Switzer-Medium.otf",
            font_size=34,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#ff474d",
            long_color="#299bb6",
        ),
        "leverage": ElementStyling(
            position=Position(0.219, 0.419),
            font="Switzer-Semibold.otf",
            font_size=34,
            color="#8c8c8c",
        ),
        "roi": ElementStyling(
            position=Position(0.059, 0.49),
            font="Switzer-Semibold.otf",
            font_size=68,
            color="#299bb6",
        ),
        "entry": ElementStyling(
            position=Position(0.381, 0.605),
            font="Switzer-Semibold.otf",
            font_size=34,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.381, 0.666),
            font="Switzer-Semibold.otf",
            font_size=34,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.267, 0.098),
            font="Switzer-Regular.otf",
            font_size=32,
            color="#8c8c8c",
        ),
        "referral": ElementStyling(
            position=Position(0.292, 0.865),
            font="Switzer-Semibold.otf",
            font_size=28,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(0.772, 0.857), size=129),
        "username": ElementStyling(
            position=Position(0.251, 0.196),
            font="Switzer-Semibold.otf",
            font_size=39,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.251, 0.251),
            font="Switzer-Medium.otf",
            font_size=30.5,
            color="#8c8c8c",
        ),
        "draw_qr_referral": True,
        "draw_datetime": True,
        "draw_username": True,
    },
    "bitget_2": {
        "symbol": ElementStyling(
            position=Position(0.067, 0.35),
            font="Switzer-Regular.otf",
            font_size=33,
            color="#888",
        ),
        "signal_type": ElementStyling(
            position=Position(0.059, 0.419),
            font="Switzer-Regular.otf",
            font_size=34,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#ff474d",
            long_color="#299bb6",
        ),
        "roi": ElementStyling(
            position=Position(0.065, 0.484),
            font="Switzer-Medium.otf",
            font_size=68,
            color=(2, 180, 210),
        ),
        "entry": ElementStyling(
            position=Position(0.322, 0.595),
            font="Switzer-Semibold.otf",
            font_size=34,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.322, 0.657),
            font="Switzer-Semibold.otf",
            font_size=34,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.267, 0.098),
            font="Switzer-Regular.otf",
            font_size=31,
            color="#8c8c8c",
        ),
        "referral": ElementStyling(
            position=Position(0.302, 0.8655),
            font="Switzer-Medium.otf",
            font_size=30,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(0.797, 0.867), size=114),
        "username": ElementStyling(
            position=Position(0.252, 0.19),
            font="Switzer-Semibold.otf",
            font_size=54,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.251, 0.251),
            font="Switzer-Regular.otf",
            font_size=35,
            color="#8c8c8c",
        ),
        "draw_qr_referral": True,
        "draw_datetime": True,
        "draw_username": True,
    },
    "mexc_1": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.3),
            font="Avenir LT Std 85 Heavy.otf",
            font_size=42,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.058, 0.365),
            font="Avenir LT Std 65 Medium.otf",
            font_size=42,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f44363",
            long_color="#18b37a",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.438),
            font="Avenir LT Std 85 Heavy.otf",
            font_size=98,
            color="#11b67a",
        ),
        "entry": ElementStyling(
            position=Position(0.268, 0.9),
            font="Avenir LT Std 65 Medium.otf",
            font_size=36,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.268, 0.85),
            font="Avenir LT Std 65 Medium.otf",
            font_size=36,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.268, 0.95),
            font="Avenir LT Std 65 Medium.otf",
            font_size=36,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "mexc_2": {
        "symbol": ElementStyling(
            position=Position(0.06, 0.248),
            font="Basier Square SemiBold.otf",
            font_size=43,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.06, 0.304),
            font="Basier Square SemiBold.otf",
            font_size=47,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f44363",
            long_color="#18b37a",
        ),
        "roi": ElementStyling(
            position=Position(0.063, 0.375),
            font="Basier Square SemiBold.otf",
            font_size=115,
            color="#11b67a",
        ),
        "entry": ElementStyling(
            position=Position(0.297, 0.702),
            font="Basier Square SemiBold.otf",
            font_size=40,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.297, 0.651),
            font="Basier Square SemiBold.otf",
            font_size=40,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.297, 0.748),
            font="Avenir LT Std 65 Medium.otf",
            font_size=42,
            color=(235, 232, 253),
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "mexc_3": {
        "symbol": ElementStyling(
            position=Position(0.06, 0.248),
            font="Basier Square SemiBold.otf",
            font_size=43,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.06, 0.304),
            font="Basier Square SemiBold.otf",
            font_size=47,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f44363",
            long_color="#18b37a",
        ),
        "roi": ElementStyling(
            position=Position(0.063, 0.375),
            font="Basier Square SemiBold.otf",
            font_size=107,
            color="#11b67a",
        ),
        "entry": ElementStyling(
            position=Position(0.425, 0.651),
            font="Basier Square SemiBold.otf",
            font_size=40,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.425, 0.702),
            font="Basier Square SemiBold.otf",
            font_size=40,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.425, 0.748),
            font="Avenir LT Std 65 Medium.otf",
            font_size=38,
            color=(235, 232, 253),
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "mexc_4": {
        "symbol": ElementStyling(
            position=Position(0.053, 0.21),
            font="Basier Square SemiBold.otf",
            font_size=40,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.053, 0.252),
            font="Basier Square SemiBold.otf",
            font_size=41,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f44363",
            long_color="#18b37a",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.307),
            font="Basier Square SemiBold.otf",
            font_size=98,
            color="#11b67a",
        ),
        "entry": ElementStyling(
            position=Position(0.255, 0.695),
            font="Basier Square SemiBold.otf",
            font_size=35,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.255, 0.738),
            font="Basier Square SemiBold.otf",
            font_size=35,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.257, 0.779),
            font="Avenir LT Std 65 Medium.otf",
            font_size=36,
            color="#dddddd",
        ),
        "referral": ElementStyling(
            position=Position(0.427, 0.88),
            font="Araboto Bold 400.ttf",
            font_size=47,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.039, 0.864), size=134),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
        "draw_qr_referral": True,
    },
    "mexc_5": {
        "symbol": ElementStyling(
            position=Position(0.055, 0.220),
            font="Basier Square SemiBold.otf",
            font_size=41,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.053, 0.265),
            font="Basier Square SemiBold.otf",
            font_size=42,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f44363",
            long_color="#18b37a",
        ),
        "roi": ElementStyling(
            position=Position(0.06, 0.320),
            font="Basier Square SemiBold.otf",
            font_size=99,
            color="#11b67a",
        ),
        "entry": ElementStyling(
            position=Position(0.255, 0.695),
            font="Basier Square SemiBold.otf",
            font_size=35,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.255, 0.738),
            font="Basier Square SemiBold.otf",
            font_size=35,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.173, 0.77),
            font="Avenir LT Std 65 Medium.otf",
            font_size=38,
            color="#dddddd",
        ),
        "referral": ElementStyling(
            position=Position(0.45, 0.875),
            font="Araboto Bold 400.ttf",
            font_size=47,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.04, 0.858), size=135),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
        "draw_qr_referral": True,
    },
    "mexc_6": {
        "symbol": ElementStyling(
            position=Position(0.053, 0.237),
            font="Basier Square SemiBold.otf",
            font_size=41,
            color="white",
        ),
        "signal_type": ElementStyling(
            position=Position(0.053, 0.289),
            font="Basier Square SemiBold.otf",
            font_size=41,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#eb4e60",
            long_color="#18b37a",
        ),
        "roi": ElementStyling(
            position=Position(0.06, 0.34),
            font="Basier Square SemiBold.otf",
            font_size=97,
            color="#11b67a",
        ),
        "entry": ElementStyling(
            position=Position(0.26, 0.707),
            font="Basier Square SemiBold.otf",
            font_size=38,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.26, 0.746),
            font="Basier Square SemiBold.otf",
            font_size=38,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.263, 0.786),
            font="Avenir LT Std 65 Medium.otf",
            font_size=38,
            color="#dddddd",
        ),
        "referral": ElementStyling(
            position=Position(0.454, 0.872),
            font="Araboto Bold 400.ttf",
            font_size=54,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.06, 0.855), size=150),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
        "draw_qr_referral": True,
    },
    "mexc_7": {
        "symbol": ElementStyling(
            position=Position(x=0.046340304182509506, y=0.30028644800186155),
            font="Basier Square SemiBold.otf",
            font_size=40,
            color="white",
        ),
        "signal_type_leverage": ElementStyling(
            position=Position(x=0.04538973384030418, y=0.3444661498069763),
            font="Araboto Normal 400.ttf",
            font_size=40,
            gap=37,
            separator_width=2,
            separator_length=40,
            signal_type_color="#de5467",
            separator_color="#999",
            leverage_color="#999",
        ),
        "roi": ElementStyling(
            position=Position(x=0.04538973384030418, y=0.4017968773841858),
            font="Pretendard-SemiBold.otf",
            font_size=96,
            color="#11b67a",
        ),
        "roi_dollars": ElementStyling(
            position=Position(x=0.046340304182509506, y=0.48851561546325684),
            font="Basier Square SemiBold.otf",
            font_size=53,
            color="#11b67a",
        ),
        "entry": ElementStyling(
            position=Position(x=0.32653675151868466, y=0.6632552027702332),
            font="Inter-Regular.ttf",
            font_size=34,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(x=0.32653675151868466, y=0.7101302027702332),
            font="Inter-Regular.ttf",
            font_size=34,
            color="white",
        ),
        "date": ElementStyling(
            position=Position(x=0.04532636345112732, y=0.10397136211395264),
            font="Inter-Regular.ttf",
            font_size=30,
            color="rgb(113, 113, 113)",
        ),
        "input_date": ElementStyling(
            position=Position(x=0.32764576959066066, y=0.7570963621139526),
            font="Inter-Regular.ttf",
            font_size=34,
            color="white",
        ),
        "referral": ElementStyling(
            position=Position(x=0.353231944965319, y=0.8305989384651185),
            font="Araboto Bold 400.ttf",
            font_size=45,
            color="white",
        ),
        "qr": ElementStyling(
            position=Position(x=0.8242554175083175, y=0.8456249952316284), size=135
        ),
    },
    "bingx_1": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.325),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.366, 0.589),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.515),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_2": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.325),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.366, 0.589),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.515),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_3": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.232),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.325),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.366, 0.589),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.515),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_4": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.35),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.36, 0.615),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.543),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_5": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.35),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.36, 0.615),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.543),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_6": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.35),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.36, 0.615),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.543),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_7": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.35),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.36, 0.615),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.543),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_8": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.35),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.36, 0.615),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.543),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "bingx_9": {
        "symbol": ElementStyling(
            position=Position(0.058, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color=(255, 255, 255),
        ),
        "signal_type": ElementStyling(
            position=Position(0.41, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            margin_x=10,
            margin_y=12,
            margin_y_mult=0.7,
            short_color="#f80064",
            long_color="#00ff9d",
        ),
        "leverage": ElementStyling(
            position=Position(0.52, 0.265),
            font="Inter-Medium.ttf",
            font_size=64.5,
            color="white",
        ),
        "roi": ElementStyling(
            position=Position(0.058, 0.35),
            font="Hezaedrus-Regular.ttf",
            font_size=175,
            color="#00ff9d",
        ),
        "entry": ElementStyling(
            position=Position(0.36, 0.615),
            font="Inter-Regular.ttf",
            font_size=46,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.262, 0.543),
            font="Inter-Regular.ttf",
            font_size=47,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.19, 0.893),
            font="Inter-Regular.ttf",
            font_size=46,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.312, 0.894),
            font="Araboto Bold 400.ttf",
            font_size=35,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.748, 0.85), size=140),
        "username": ElementStyling(
            position=Position(0.215, 0.195),
            font="Araboto Black 400.ttf",
            font_size=55,
            color="white",
        ),
        "username_id": ElementStyling(
            position=Position(0.22, 0.257),
            font="Araboto Normal 400.ttf",
            font_size=35,
            color=(124, 125, 127),
        ),
        "draw_datetime": True,
    },
    "okx_1": {
        "symbol": ElementStyling(
            position=Position(0.0545, 0.234),
            font="MADE Evolve Sans Medium (PERSONAL USE).otf",
            font_size=44,
            color="white",
        ),
        "signal_type_leverage": ElementStyling(
            position=Position(0.055, 0.29),
            font="MADE Evolve Sans Regular (PERSONAL USE).otf",
            font_size=35,
            color="#888888",
        ),
        "roi": ElementStyling(
            position=Position(0.056, 0.355),
            font="SFTSchriftedSansTRIAL-DemiBoldComp-BF6413e1edd8f93.otf",
            font_size=122,
            color=(26, 169, 77),
        ),
        "entry": ElementStyling(
            position=Position(0.26, 0.518),
            font="Avenir LT Std 65 Medium.otf",
            font_size=33,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.26, 0.57),
            font="Avenir LT Std 65 Medium.otf",
            font_size=33,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.68, 0.102),
            font="schemebk-regular.otf",
            font_size=26,
            color="#888888",
        ),
        "referral": ElementStyling(
            position=Position(0.252, 0.8615),
            font="Avenir LT Std 85 Heavy.otf",
            font_size=28.5,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(0.802, 0.865), size=120),
        "draw_datetime": True,
        "draw_qr_referral": True,
    },
    "lbank_1": {
        "symbol": ElementStyling(
            position=Position(0.069, 0.163),
            font="Yantramanav-Black.ttf",
            font_size=30,
            color="white",
        ),
        "futures_rrect": ElementStyling(
            x_spacing=20,
            y_spacing=7,
            rect_radius=15,
            padding_x=9,
            padding_y=2,
            box_color=(45, 46, 51),
            text_color="white",
            font="Yantramanav-Regular.ttf",
            box_height=30,
            box_width=80,
            font_size=20,
        ),
        "signal_type": ElementStyling(
            position=Position(0.07, 0.207),
            font="Yantramanav-Regular.ttf",
            font_size=30,
            color=(187, 92, 112),
        ),
        "leverage": ElementStyling(color="#888888"),
        "roi": ElementStyling(
            position=Position(0.07, 0.355),
            font="Yantramanav-Black.ttf",
            font_size=85,
            color=(35, 181, 132),
        ),
        "entry": ElementStyling(
            position=Position(0.07, 0.585),
            font="Yantramanav-Regular.ttf",
            font_size=30,
            color="white",
        ),
        "target": ElementStyling(
            position=Position(0.07, 0.7),
            font="Yantramanav-Regular.ttf",
            font_size=30,
            color="white",
        ),
        "gen_date": ElementStyling(
            position=Position(0.636, 0.077),
            font="Yantramanav-Regular.ttf",
            font_size=22,
            color="#aaaaaa",
        ),
        "referral": ElementStyling(
            position=Position(0.361, 0.853),
            font="Yantramanav-Black.ttf",
            font_size=30,
            color="white",
        ),
        "qr_code": ElementStyling(position=Position(0.815, 0.866), size=83),
        "draw_datetime": True,
        "draw_qr_referral": True,
    },
    "lbank_2": {
        "symbol": ElementStyling(
            position=Position(0.069, 0.163),
            font="Yantramanav-Black.ttf",
            font_size=30,
            color="black",
        ),
        "futures_rrect": ElementStyling(
            x_spacing=20,
            y_spacing=7,
            rect_radius=15,
            padding_x=9,
            padding_y=2,
            box_color=(237, 238, 240),
            text_color="black",
            font="Yantramanav-Regular.ttf",
            box_height=30,
            box_width=80,
            font_size=20,
        ),
        "signal_type": ElementStyling(
            position=Position(0.07, 0.207),
            font="Yantramanav-Regular.ttf",
            font_size=30,
            short_color=(187, 92, 112),
            long_color=(35, 181, 132),
        ),
        "leverage": ElementStyling(color="black"),
        "roi": ElementStyling(
            position=Position(0.07, 0.355),
            font="Yantramanav-Black.ttf",
            font_size=85,
            color=(35, 181, 132),
        ),
        "entry": ElementStyling(
            position=Position(0.07, 0.585),
            font="Yantramanav-Regular.ttf",
            font_size=30,
            color="black",
        ),
        "target": ElementStyling(
            position=Position(0.07, 0.7),
            font="Yantramanav-Regular.ttf",
            font_size=30,
            color="black",
        ),
        "gen_date": ElementStyling(
            position=Position(0.636, 0.077),
            font="Yantramanav-Regular.ttf",
            font_size=22,
            color="black",
        ),
        "referral": ElementStyling(
            position=Position(0.361, 0.853),
            font="Yantramanav-Black.ttf",
            font_size=30,
            color="black",
        ),
        "qr_code": ElementStyling(position=Position(0.815, 0.866), size=83),
        "draw_datetime": True,
        "draw_qr_referral": True,
    },
}
